export PS1='\e[34m\e[1m❯❯❯\e(B\e[m '

export QT_QPA_PLATFORMTHEME=qt5ct
#force use of gtk3-nocsd
export GTK_CSD=0
export LD_PRELOAD=/usr/lib/libgtk3-nocsd.so.0

alias lsblk='lsblk -f'
alias radeontop='radeontop -c'
alias cpr='rclone copy --progress'
alias cps='rclone sync --progress'
alias rm='trash-put'
alias :q='exit'
alias vifm='rm ~/.config/vifm/vifminfo.json; /bin/vifm'
alias yt-mp3='youtube-dl --add-header "Cookie:" --extract-audio --audio-format mp3'
alias steam='LD_PRELOAD="~/.config/altlibsteam/sdl_block_screensaver_inhibit.so" SDL_VIDEO_ALLOW_SCREENSAVER=1 /bin/steam -silent -no-browser steam://open/minigameslist'

if [ $(tty) != '/dev/tty1' ]
then
	tmux attach -t DEFAULT 2> /dev/null || tmux new -s DEFAULT 2> /dev/null
fi
