#!/bin/bash
transmission-daemon --port 9091 --allowed "127.0.0.1" -T &
xrdb -merge ~/.config/Xresources &
unclutter -idle 2 -jitter 4 &
flameshot &
sxhkd &
audacious -H &

setxkbmap -layout pl
xmodmap -e "clear mod4"
xmodmap -e "clear mod3"
#xmodmap -e "keycode 104 = Super_L"
xmodmap -e "keycode 135 = Super_R"
xmodmap -e "keycode 133 = Super_R"
#xmodmap -e "add mod4 = Super_L"
xmodmap -e "add mod3 = Super_R"
xmodmap -e "keycode 91 = period period"
xmodmap -e "keycode 52 = z Z z Z zstroke Zstroke"
#xset -dpms
