#!/bin/sh

Tasten &
sleep 1
sudo Tasten-client -d usb-SIGMACHIP_USB_Keyboard-event-kbd &
audacious -H &

wmctrl -s 4
transmission-gtk &
alacritty -e 'htop' &
sleep 0.5
wmctrl -r :ACTIVE: -e 0,960,549,956,527
ripcord &
sleep 5
pavucontrol &
sleep 0.5
wmctrl -r :ACTIVE: -e 0,0,549,956,527
wmctrl -s 0
falkon &

xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'keycode 91 = Delete period period Delete'
