#!/bin/sh

sleep 1.4
boty &
firefox &
sleep 4

xdotool key Super_L+F5
alacritty -e 'htop' &
sleep 0.5
xdotool key Super_L+c
#transmission-gtk &
audacious &
sleep 0.7
xdotool key Super_L+z
pavucontrol &
sleep 0.5
xdotool key Super_L+w
xdotool key Super_L+F4
ripcord &
sleep 1
xdotool key Super_L+F2
################

xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'keycode 91 = Delete period period Delete'
