#!/bin/sh

Tasten &
sleep 1.4
firefox &
sudo Tasten-client -d event14 &
audacious -H &
sleep 4

wmctrl -s 4
alacritty -e 'htop' &
sleep 0.5
wmctrl -r :ACTIVE: -e 0,960,549,956,527
transmission-gtk &
sleep 4
pavucontrol &
sleep 0.5
wmctrl -r :ACTIVE: -e 0,0,18,1916,527

wmctrl -s 3
ripcord &
sleep 1
wmctrl -s 1

xmodmap -e 'keycode 135 = Super_R'
xmodmap -e 'keycode 91 = Delete period period Delete'
